### PR TITLE
[3] HTML and CSS

### PR DESCRIPTION
**Pull request by ysmaliak**

### CODE REVIEW

**Comment by gmltA** [comment]
Deployment?

**Comment by ysmaliak** [comment]
https://ysmaliak.github.io/GroceryList-WebApp/src/index
https://ysmaliak.github.io/GroceryList-WebApp/src/login

**Comment by ysmaliak** [comment]
It turned out that making a design is much easier than implementing it. And I completely forgot about the markup while I was trying to make something that looked like a picture. I will fix some bugs.
Also, I am sure that I made childish mistakes that I do not notice

**Comment by ysmaliak** [comment]
It turned out that making a design is much easier than implementing it. And I completely forgot about the markup while I was trying to make something that looked like a picture.
Also, I am sure that I made childish mistakes that I do not notice

**Comment by gmltA** [comment]
> It turned out that making a design is much easier than implementing it. And I completely forgot about the markup while I was trying to make something that looked like a picture.
> Also, I am sure that I made childish mistakes that I do not notice

So... are you going to fix that? I'm asking mainly about HTML tags.

**Review by gmltA — APPROVED** [review]
Good. That's a <kbd>9</kbd>.

**Pull request merged**
