### PR TITLE
[2] Design

### PR DESCRIPTION
**Pull request by ysmaliak**

### CODE REVIEW

**Review by gmltA — COMMENTED** [review]
image

As for now, you have some errors in your markup.

`<body>` is a whole body of your HTML document. You can't use it inside.
`<button>`  is a stateless clickable component. I suppose the marker on the left of your list item supposed to act like a radio or a checkbox.

As for now, I can offer you <kbd>5</kbd>, due to aforementioned errors and shortage of used tags.

To improve it, I'd ask you to show me a markup for this page as detailed as possible (including dropdown menu when you click on the profile (if any), page parts (`header, footer, main`) and a structure of your list).

image

**Comment by ysmaliak** [comment]
Yes, there is a drop-down menu, you can see it on the next screen, and I will redo the markup because I definitely want to get a higher grade
Screenshot 2021-02-23 at 17 47 59

**Comment by ysmaliak** [comment]
IDK if I made any progress, but at least my markup looks much prettier now. I'd also recommend [seeing design and markup in Figma](https://www.figma.com/file/UhoU802zFXxXRGe0FQZytN/GroceryList-WebApp?node-id=0%3A1).

**Review by gmltA — APPROVED** [review]
Good. Now that's a solid <kbd>9</kbd>.

**Pull request merged**
