### PR TITLE
[4] JS

### PR DESCRIPTION
**Pull request by ysmaliak**

### CODE REVIEW

**Review by gmltA — APPROVED** [review]
Good. That's a <kbd>9</kbd>. What's left?

**Comment by ysmaliak** [comment]
Looks like nothing left, I already did everything including CI set-up.

**Comment by gmltA** [comment]
Okay. Then <kbd>9</kbd> is the resulting mark in this semester.

Good luck!

**Comment by ysmaliak** [comment]
Thanks!

**Comment by ysmaliak** [comment]
Thanks!

**Pull request merged**
